// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TLOSoltuion.Data.EF;

namespace TLOSoltuion.Data.Migrations
{
    [DbContext(typeof(TLODbContext))]
    [Migration("20210709162650_latest")]
    partial class latest
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "b5b2f7f7-36bc-4685-9543-4fa2271ccede",
                            ConcurrencyStamp = "a9abe8b8-5d9d-4b3a-8faf-e8f40b9172c2",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "767205ac-b5ab-42f6-a48b-e5023a6f4549",
                            ConcurrencyStamp = "f136dace-14e4-43d6-b42b-4f9e42a23e4b",
                            Name = "Publisher",
                            NormalizedName = "PUBLISHER"
                        },
                        new
                        {
                            Id = "4067a657-29d1-4588-baaa-b7c93d9626a4",
                            ConcurrencyStamp = "55587c4a-2453-4d9b-afc1-0eeb591bc464",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("TLOSoltuion.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagepath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Luận văn đại học, cao học, tiếng anh, các đề tài nghiên cứu",
                            Imagepath = "/image-content/category/LuanVanBaoCao.png",
                            Name = "Luận văn - báo cáo"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Tài liệu lĩnh vực công nghệ thông tin",
                            Imagepath = "/image-content/category/CNTT.png",
                            Name = "Công nghệ thông tin"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Tài liệu về các kỹ năng tư duy, quản lý, giao tiếp, đối nhân xử thế",
                            Imagepath = "/image-content/category/KNMem.png",
                            Name = "Kỹ năng mềm"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Quản trị, internet, marketing",
                            Imagepath = "/image-content/category/KinhDoanh.png",
                            Name = "Kinh doanh - tiếp thị"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Tài liệu về kinh tế, quản lý",
                            Imagepath = "/image-content/category/KinhTeQuanLy.png",
                            Name = "Kinh tế - Quản lý"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Báo cáo tài chính, kế toán,...",
                            Imagepath = "/image-content/category/LuanVanBaoCao.png",
                            Name = "Tài chính - ngân hàng"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Biểu mẫu, văn bản, đơn, thư từ, thủ tục",
                            Imagepath = "/image-content/category/BieuMauVanBan.png",
                            Name = "Biểu mẫu - Văn bản"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Tài liệu về đề thi, câu hỏi",
                            Imagepath = "/image-content/category/GiaoDuc.png",
                            Name = "Giáo dục đào tạo"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Tài liệu về các bài giảng môn học",
                            Imagepath = "/image-content/category/BaiGiang.png",
                            Name = "Giáo án bài giảng"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Thông tư, nghị định, pháp lệnh",
                            Imagepath = "/image-content/category/PhapLuat.jpg",
                            Name = "Văn bản pháp luật"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Các tài liệu liên quan đến học tiếng anh, giao tiếp,...",
                            Imagepath = "/image-content/category/English.jpg",
                            Name = "Học tiếng Anh"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Các bài văn khấn nôm",
                            Imagepath = "/image-content/category/VanKhanNom.png",
                            Name = "Các bài văn khấn nôm"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Các mẫu slide đẹp",
                            Imagepath = "/image-content/category/MauSlide.png",
                            Name = "Mẫu slide"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Nấu ăn, mẹo vặt, hoạt động,...",
                            Imagepath = "/image-content/category/PhapLuat.jpg",
                            Name = "Lĩnh vực khác"
                        });
                });

            modelBuilder.Entity("TLOSoltuion.Data.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DowloadCount")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Post");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Khái niệm, và các thành phần liên quan của polyme blend",
                            DocumentPath = "/content/LuanVan1pdf.pdf",
                            DocumentType = "pdf",
                            DowloadCount = 25,
                            ImagePath = "/image-content/post/LuanVan1.png",
                            Title = "TỔNG QUAN VỀ VẬT LIỆU POLYME BLEND",
                            UserId = "2dce503c-3842-4350-891b-c4c339882ece",
                            ViewCount = 12
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Cách thức nuôi cấy, cấu tạo tế bào thực vật",
                            DocumentPath = "/content/LuanVan2pdf.pdf",
                            DocumentType = "pdf",
                            DowloadCount = 36,
                            ImagePath = "/image-content/post/LuanVan2.png",
                            Title = "NUÔI CẤY MÔ - TẾ BÀO THỰC VẬT",
                            UserId = "2dce503c-3842-4350-891b-c4c339882ece",
                            ViewCount = 15
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Đào tạo nguồn lực cho sự nghiệp giáo dục",
                            DocumentPath = "/content/LuanVan3pdf.pdf",
                            DocumentType = "pdf",
                            DowloadCount = 50,
                            ImagePath = "/image-content/post/LuanVan3.png",
                            Title = "ĐÀO TẠO NGUỒN LỰC CHO SỰ NGHIỆP GIÁO DỤC",
                            UserId = "2dce503c-3842-4350-891b-c4c339882ece",
                            ViewCount = 26
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "GIỚI THIỆU BOOTSTRAP",
                            DocumentPath = "/content/CNTT1pdf.pdf",
                            DocumentType = "pdf",
                            DowloadCount = 50,
                            ImagePath = "/image-content/post/CNTT1.png",
                            Title = "GIỚI THIỆU BOOTSTRAP",
                            UserId = "2dce503c-3842-4350-891b-c4c339882ece",
                            ViewCount = 26
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "HƯỚNG DẪN ASP",
                            DocumentPath = "/content/CNTT2pdf.pdf",
                            DocumentType = "pdf",
                            DowloadCount = 120,
                            ImagePath = "/image-content/post/CNTT2.png",
                            Title = "XÂY DỰNG ỨNG DỤNG ASP",
                            UserId = "2dce503c-3842-4350-891b-c4c339882ece",
                            ViewCount = 39
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Giới thiệu REACTjs cơ bản",
                            DocumentPath = "/content/CNTT3pdf.pdf",
                            DocumentType = "pdf",
                            DowloadCount = 120,
                            ImagePath = "/image-content/post/CNTT3.png",
                            Title = "HỌC REACTJS CƠ BẢN",
                            UserId = "2dce503c-3842-4350-891b-c4c339882ece",
                            ViewCount = 39
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "KỸ NĂNG CÔ GIÁO MẦM NON",
                            DocumentPath = "/content/KN1pdf.pdf",
                            DocumentType = "pdf",
                            DowloadCount = 120,
                            ImagePath = "/image-content/post/KN1.jpg",
                            Title = "KỸ NĂNG CÔ GIÁO MẦM NON",
                            UserId = "2dce503c-3842-4350-891b-c4c339882ece",
                            ViewCount = 39
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "KỸ NĂNG GIAO TIẾP",
                            DocumentPath = "/content/KN2pdf.pdf",
                            DocumentType = "pdf",
                            DowloadCount = 120,
                            ImagePath = "/image-content/post/KN2.jpg",
                            Title = "KỸ NĂNG GIAO TIẾP",
                            UserId = "2dce503c-3842-4350-891b-c4c339882ece",
                            ViewCount = 39
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "KỸ NĂNG QUẢN LÝ THỜI GIAN",
                            DocumentPath = "/content/KN3pdf.pdf",
                            DocumentType = "pdf",
                            DowloadCount = 120,
                            ImagePath = "/image-content/post/KN3.jpg",
                            Title = "KỸ NĂNG QUẢN LÝ THỜI GIAN",
                            UserId = "2dce503c-3842-4350-891b-c4c339882ece",
                            ViewCount = 39
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Description = "SÁCH KINH DOANH",
                            DocumentPath = "/content/KD1pdf.pdf",
                            DocumentType = "pdf",
                            DowloadCount = 120,
                            ImagePath = "/image-content/post/KD1.png",
                            Title = "KHỞI NGHIỆP TINH GỌN",
                            UserId = "2dce503c-3842-4350-891b-c4c339882ece",
                            ViewCount = 39
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            Description = "SÁCH HAY KINH DOANH",
                            DocumentPath = "/content/KD2pdf.pdf",
                            DocumentType = "pdf",
                            DowloadCount = 120,
                            ImagePath = "/image-content/post/KD2.png",
                            Title = "NGƯỜI GIÀU CÓ NHẤT THÀNH BABYLON",
                            UserId = "2dce503c-3842-4350-891b-c4c339882ece",
                            ViewCount = 39
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Description = "SÁCH HAY KINH DOANH",
                            DocumentPath = "/content/KD3pdf.pdf",
                            DocumentType = "pdf",
                            DowloadCount = 120,
                            ImagePath = "/image-content/post/KD3.png",
                            Title = "CHA GIÀU CHA NGHÈO",
                            UserId = "2dce503c-3842-4350-891b-c4c339882ece",
                            ViewCount = 39
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            Description = "SÁCH HAY VỀ QUẢN LÝ",
                            DocumentPath = "/content/KT1pdf.pdf",
                            DocumentType = "pdf",
                            DowloadCount = 120,
                            ImagePath = "/image-content/post/KT1.png",
                            Title = "NGHỀ QUẢN LÝ",
                            UserId = "2dce503c-3842-4350-891b-c4c339882ece",
                            ViewCount = 39
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            Description = "SÁCH HAY QUẢN LÝ",
                            DocumentPath = "/content/KT2pdf.pdf",
                            DocumentType = "pdf",
                            DowloadCount = 120,
                            ImagePath = "/image-content/post/KT2.png",
                            Title = "SÁCH QUẢN TRỊ NGUỒN LỰC",
                            UserId = "2dce503c-3842-4350-891b-c4c339882ece",
                            ViewCount = 39
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            Description = "QUẢN LÝ TÀI CHÍNH",
                            DocumentPath = "/content/KT3pdf.pdf",
                            DocumentType = "pdf",
                            DowloadCount = 120,
                            ImagePath = "/image-content/post/KT2.png",
                            Title = "QUẢN LÝ TÀI CHÍNH",
                            UserId = "2dce503c-3842-4350-891b-c4c339882ece",
                            ViewCount = 39
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 6,
                            Description = "QUẢN LÝ TÀI CHÍNH",
                            DocumentPath = "/content/TC1pdf.pdf",
                            DocumentType = "pdf",
                            DowloadCount = 120,
                            ImagePath = "/image-content/post/TC1.png",
                            Title = "TIỀN VÀ HOẠT ĐỘNG NGÂN HÀNG",
                            UserId = "2dce503c-3842-4350-891b-c4c339882ece",
                            ViewCount = 39
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 6,
                            Description = "QUẢN LÝ TÀI CHÍNH",
                            DocumentPath = "/content/TC2pdf.pdf",
                            DocumentType = "pdf",
                            DowloadCount = 120,
                            ImagePath = "/image-content/post/TC2.png",
                            Title = "TRÍ TUỆ TÀI CHÍNH",
                            UserId = "2dce503c-3842-4350-891b-c4c339882ece",
                            ViewCount = 39
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 6,
                            Description = "SÁCH HAY VỀ TÀI CHÍNH",
                            DocumentPath = "/content/TC3pdf.pdf",
                            DocumentType = "pdf",
                            DowloadCount = 120,
                            ImagePath = "/image-content/post/TC3.png",
                            Title = "TOÁN TÀI CHÍNH",
                            UserId = "2dce503c-3842-4350-891b-c4c339882ece",
                            ViewCount = 39
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 7,
                            Description = "HỢP ĐỒNG THUÊ NHÀ",
                            DocumentPath = "/content/VB1pdf.pdf",
                            DocumentType = "pdf",
                            DowloadCount = 120,
                            ImagePath = "/image-content/post/VB1.png",
                            Title = "HỢP ĐỒNG THUÊ NHÀ",
                            UserId = "2dce503c-3842-4350-891b-c4c339882ece",
                            ViewCount = 39
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 7,
                            Description = "ĐƠN XIN VIỆC",
                            DocumentPath = "/content/VB2pdf.pdf",
                            DocumentType = "pdf",
                            DowloadCount = 120,
                            ImagePath = "/image-content/post/VB2.png",
                            Title = "ĐƠN XIN VIỆC",
                            UserId = "2dce503c-3842-4350-891b-c4c339882ece",
                            ViewCount = 39
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 7,
                            Description = "ĐƠN KHIẾU NẠI",
                            DocumentPath = "/content/VB3pdf.pdf",
                            DocumentType = "pdf",
                            DowloadCount = 120,
                            ImagePath = "/image-content/post/VB3.png",
                            Title = "ĐƠN KHIẾU NẠI",
                            UserId = "2dce503c-3842-4350-891b-c4c339882ece",
                            ViewCount = 39
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 8,
                            Description = "ĐỀ THI",
                            DocumentPath = "/content/GD1pdf.pdf",
                            DocumentType = "pdf",
                            DowloadCount = 120,
                            ImagePath = "/image-content/post/GD1.png",
                            Title = "ĐỀ THI TOÁN 2019",
                            UserId = "2dce503c-3842-4350-891b-c4c339882ece",
                            ViewCount = 39
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 8,
                            Description = "ĐỀ THI CẤP 3",
                            DocumentPath = "/content/GD2pdf.pdf",
                            DocumentType = "pdf",
                            DowloadCount = 120,
                            ImagePath = "/image-content/post/GD2.png",
                            Title = "ĐỀ THI CẤP 3 HÀ NỘI 2019",
                            UserId = "2dce503c-3842-4350-891b-c4c339882ece",
                            ViewCount = 39
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 8,
                            Description = "TÀI LIỆU",
                            DocumentPath = "/content/GD3pdf.pdf",
                            DocumentType = "pdf",
                            DowloadCount = 25,
                            ImagePath = "/image-content/post/GD3.png",
                            Title = "TÀI LIỆU ÔN THI THPT 2019",
                            UserId = "2dce503c-3842-4350-891b-c4c339882ece",
                            ViewCount = 56
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 9,
                            Description = "TÀI LIỆU",
                            DocumentPath = "/content/BG1pdf.pdf",
                            DocumentType = "pdf",
                            DowloadCount = 25,
                            ImagePath = "/image-content/post/BG1.png",
                            Title = "BÀI GIẢNG MÔN AN TOÀN HỆ ĐIỀU HÀNH",
                            UserId = "2dce503c-3842-4350-891b-c4c339882ece",
                            ViewCount = 56
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 9,
                            Description = "TÀI LIỆU",
                            DocumentPath = "/content/BG2pdf.pdf",
                            DocumentType = "pdf",
                            DowloadCount = 25,
                            ImagePath = "/image-content/post/BG2.png",
                            Title = "BÀI GIẢNG AN TOÀN HỆ ĐIỀU HÀNH",
                            UserId = "2dce503c-3842-4350-891b-c4c339882ece",
                            ViewCount = 56
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 9,
                            Description = "TÀI LIỆU",
                            DocumentPath = "/content/BG3pdf.pdf",
                            DocumentType = "pdf",
                            DowloadCount = 25,
                            ImagePath = "/image-content/post/BG3.png",
                            Title = "BÀI GIẢNG USE CASE CNPM",
                            UserId = "2dce503c-3842-4350-891b-c4c339882ece",
                            ViewCount = 56
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 10,
                            Description = "VĂN BẢN PHÁP LUẬT",
                            DocumentPath = "/content/VBPL.pdf",
                            DocumentType = "pdf",
                            DowloadCount = 100,
                            ImagePath = "/image-content/post/PL1.png",
                            Title = "CƠ SỞ DỮ LIỆU VĂN BẢN PHÁP LUẬT",
                            UserId = "2dce503c-3842-4350-891b-c4c339882ece",
                            ViewCount = 200
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 11,
                            Description = "TIẾNG ANH NGỮ ÂM HAY",
                            DocumentPath = "/content/TA1pdf.pdf",
                            DocumentType = "pdf",
                            DowloadCount = 25,
                            ImagePath = "/image-content/post/TA1.png'",
                            Title = "HỌC NGỮ ÂM",
                            UserId = "2dce503c-3842-4350-891b-c4c339882ece",
                            ViewCount = 56
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 11,
                            Description = "TÀI LIỆU TIẾNG ANH",
                            DocumentPath = "/content/TA2pdf.pdf",
                            DocumentType = "pdf",
                            DowloadCount = 25,
                            ImagePath = "/image-content/post/TA2.png",
                            Title = "HỌC TỪ VỰNG",
                            UserId = "2dce503c-3842-4350-891b-c4c339882ece",
                            ViewCount = 56
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 12,
                            Description = "VĂN HỌC",
                            DocumentPath = "/content/V1pdf.pdf",
                            DocumentType = "pdf",
                            DowloadCount = 25,
                            ImagePath = "/image-content/post/V1.png",
                            Title = "CÁC BÀI VĂN KHẤN NÔM",
                            UserId = "2dce503c-3842-4350-891b-c4c339882ece",
                            ViewCount = 56
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 13,
                            Description = "SLIDE",
                            DocumentPath = "/content/SL1pdf.pdf",
                            DocumentType = "pdf",
                            DowloadCount = 25,
                            ImagePath = "/image-content/post/SL1.png",
                            Title = "MẪU SLIDE CẢM ƠN ĐẸP",
                            UserId = "2dce503c-3842-4350-891b-c4c339882ece",
                            ViewCount = 56
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 13,
                            Description = "SLIDE",
                            DocumentPath = "/content/SL2pdf.pdf",
                            DocumentType = "pdf",
                            DowloadCount = 25,
                            ImagePath = "/image-content/post/SL1.png",
                            Title = "MẪU SLIDE ĐẸP",
                            UserId = "2dce503c-3842-4350-891b-c4c339882ece",
                            ViewCount = 56
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 14,
                            Description = "EBOOK NẤU ĂN HAY",
                            DocumentPath = "/content/K1pdf.pdf",
                            DocumentType = "pdf",
                            DowloadCount = 25,
                            ImagePath = "/image-content/post/K1.png",
                            Title = "SÁCH DẠY NẤU ĂN",
                            UserId = "2dce503c-3842-4350-891b-c4c339882ece",
                            ViewCount = 56
                        });
                });

            modelBuilder.Entity("TLOSoltuion.Data.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "2dce503c-3842-4350-891b-c4c339882ece",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7a3db7d8-f867-49da-9e29-340eafc42f6d",
                            Dob = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "publisher@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Publiser 1",
                            LastName = "TailieuOnline",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "30de84a1-54ad-449b-89ed-13c3cac68d0b",
                            TwoFactorEnabled = false,
                            UserName = "publisher@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TLOSoltuion.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TLOSoltuion.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TLOSoltuion.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TLOSoltuion.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TLOSoltuion.Data.Entities.Post", b =>
                {
                    b.HasOne("TLOSoltuion.Data.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TLOSoltuion.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
